import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import TabBar from '@/components/TabBar';
import FormItem from '@/components/FormItem';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TabBar
        labels={[
          'test1',
          'test2',
          'test3',
          'test4',
          'test5',
          'test6',
          'test7',
          'test8',
        ]}
      />
      <FormItem variant="large" label="테스트" placeholder="test" />
      <FormItem variant="small" label="테스트2" placeholder="test2" />
    </>
  );
}
